all:
  children:
    webservers:
      hosts:
        lab01:
          ansible_host: 192.168.64.2
        lab02:
          ansible_host: 192.168.64.3
  vars:
    ansible_user: minkyluv
    ansible_ssh_private_key_file: ~/.ssh/id_ecdsa
    ansible_python_interpreter: /usr/bin/python3.9
